import Head from "next/head";

export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Vijeth ☀</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='max-w-xl'>
        <h1 className='text-3xl font-bold '>this is a portfolio website</h1>
      </main>

      <footer className=''></footer>
    </div>
  );
}
